[defaults]
name="default name"
cmd="echo no command set"
quit_fast=false

[[runners]]
name="rust run"
cmd="cargo run"
quit_fast=false

[[runners]]
name="echo var showcase"
cmd="echo {myvar}"
quit_fast=false

[[runners]]
name="unique"
cmd="{command}"
quit_fast=false
